version: "3.9"

services:
  query:
    container_name: query
    ports:
      - ${QUERY_APP_PORT}:${QUERY_APP_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port ${QUERY_APP_PORT}"

  command:
    container_name: command
    ports:
      - ${COMMAND_APP_PORT}:${COMMAND_APP_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port ${COMMAND_APP_PORT}"